### ISSUE TITLE
Internal error or misconfiguration and was unable to complete you request.

### ISSUE THREAD

**Issue by jiatao99** [mplx/docker-webvirtcloud#8]
I can add/edit Computes using TCP though GUI.

However, when I add a new instance, I got 500 error.

Navigate to the instance tab, the instance is there, click it got the same error. Also I can start, stop, restart it. 

In the host, `nirsh list --all` does show it is running. Click on the novnc got another error screen. Any idea?

**Comment by jiatao99** [comment]
After I create another super user and run under that user, the 500 error went away.

However, when I click on view(novnc) button, I still get this error: "Something went wrong, connection is close"

**Comment by zl875136491** [comment]
I found the root cause. 
The right thing to do: click on the pinion on the admin card in the user view and modify the quota for admin users, including Max instances,Max cpus,Max memory and Max disk size. 
(The value is arbitrary, but it is best to fill in it according to the actual situation of the physical machine. ) 
The reason for this BUG: in /srv/webvirtcloud/instances/views.py, you need to calculate the user's quota before you can proceed to the next step, but if you do not set the limit, the data cannot be found in the database and cause an error. 
It is recommended that developers add a default minimum quota for admin during admin initialization.
